### ISSUE TITLE
Module 12: EDA

### ISSUE THREAD

**Issue by jeweluzquiano** [r4wrds/r4wrds#100]
When you are plotting the well use types in ggplot the second time for Question #1, there is a line: guides(fill = FALSE) which returns the error:
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.

**Comment by richpauloo** [comment]
Thanks Jewel. We'll update this warning message when we re-build the course. 

In general, turning "off" legends in ggplot is now accomplished by `guides(<scale> = "none")` where `<scale>` is `color`, `fill`, `size`, etc.

**Comment by ryanpeek** [comment]
Addressed with #104
