### ISSUE TITLE
simplify pathnames and drop {here} except were critically needed...

### ISSUE THREAD

**Issue by ryanpeek** [r4wrds/r4wrds#119]
Given the mental models new learners come in with (0️⃣), suggest dropping using the `{here}` package. It adds extra abstraction when teaching relative paths, and it's probably best to introduce briefly if covering Rmarkdown documents. Would help standardize code, encourage using tab autocomplete, relative paths, and remove dependency.

**Comment by richpauloo** [comment]
- [ ] complete for intro see #123 
- [ ] repeat for intermediate

**Comment by richpauloo** [comment]
Closed by #125
