### ISSUE TITLE
environmental variables--sys.getenv

### ISSUE THREAD

**Issue by lisamr** [r4wrds/r4wrds#126]
Sys.getenv("USER") returns an empty string for me, but Sys.getenv("USERNAME") returns expected username.  Was "USER" defined in a previous lesson bc by default, I don't think it exists.

**Comment by richpauloo** [comment]
Curious. I get:

```
> Sys.getenv("USER")
[1] "richpauloo"
> Sys.getenv("USERNAME")
[1] ""
> R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie  
```

In past courses, we've always had success with `Sys.getenv("USER")`, and most participants are on Windows. 

Also, great job bringing this to Github so we can tag these issues with PRs that close them!

I'll leave open for now. Perhaps just a good thing to know when teaching the course, and I suppose you can make the rest of the lesson flow by setting:

```
Sys.setenv("USER") <- "lisarosenthal"
```

Thoughts?

**Comment by richpauloo** [comment]
Okay a todo for me or Ryan later:

- [ ] add windows “USERNAME” env var and reknit 

and sorry I misspoke, the syntax is 

`Sys.setenv(USER = “lisa”)`

**Comment by ryanpeek** [comment]
@richpauloo @lisamr 
Hey all just seeing this...sorry for the (very) delayed response. I suggest using a platform independent approach. This works on both windows and osx and linux machines (I believe): 
`Sys.info()[["user"]]`
So I suggest switching to that where necessary. I don't remember where this is used.

**Comment by lisamr** [comment]
It's under ".Renviron" in https://www.r4wrds.com/intermediate/m_project_management

I just tested it on this computer (windows) and it works.

**Comment by ryanpeek** [comment]
Hi @lisamr just to clarify, you tested the `Sys.info[["user"]]` approach?

**Comment by lisamr** [comment]
Yes, sys.info[[“users”]] worked on my windows machine, haven’t tested on a
Mac

**Comment by richpauloo** [comment]
Yup. Good job folks! PR #135 closes this.
