### ISSUE TITLE
need to fix link to messy spreadsheets...

### ISSUE THREAD

**Issue by ryanpeek** [r4wrds/r4wrds#137]
@richpauloo 

For messy spreadsheet lesson, that link is within zipped file for dataset, perhaps we need to re-write to say "data is in this location: "`data/calenviroscreen/ces3results_messy.xlsx`", and can be found in zipped format here:"

https://github.com/r4wrds/r4wrds/blob/da7affe639564803573a9a6a078d221eeaed5170/intro/m_pivots.Rmd#L73

The fig references also seem a bit odd but can deal with that later.

**Comment by richpauloo** [comment]
Closed by #138
