### ISSUE TITLE
findNLDI bug

### ISSUE THREAD

**Issue by richpauloo** [r4wrds/r4wrds#77]
@ryanpeek - I'm trying to rebuild the site with twitter cards and a CC license for all images and text, and running into a weird bug in `intro/m_functions.R`:

```
library(sf)

# get NWIS and flowline data 50km downstream of the USGS gage
amer_ds_nimbus <- findNLDI(
  nwis = "11446500", # Below Nimbus Dam
  nav = c("UM","DM"), 
  find = c("nwis", "flowlines"),
  distance_km = 50)

names(amer_ds_nimbus)
```

returns: 

```
Error in data.frame(url = unlist(c(start_url, if (getBasin) { : 
  arguments imply differing number of rows: 8, 7
Calls: <Anonymous> ... withVisible -> eval -> eval -> findNLDI -> data.frame
```

Any idea?

**Comment by ryanpeek** [comment]
try updating your `{dataRetrieval}` or `{sf}` packages... I ran this and didn't run into any errors.

**Comment by ldecicco-USGS** [comment]
We're actually just fixing a new bug that crept up in there with some updates to that NLDI service. There's  a PR going to be merged in the next day or two....

**Comment by ryanpeek** [comment]
awesome! thanks for heads up

**Comment by richpauloo** [comment]
Heads up that this issue impacts `m_advanced_spatial.R`, which fails to knit:

```
label: dataRetrieval-nldi
  |..............................................                        |  66%
  ordinary text without R code

  |...............................................                       |  68%
label: filter-nldi

Error: 
usgs_stations does not contain data 
Execution halted
```

We need to address this before the class, and generally be aware of it.

**Comment by ryanpeek** [comment]
this chunk is actually fixed now...had to do with the slightly different USGS return in the `identifier` column. Now the service is currently down, so will flag this as this chunk that needs to be run and saved out as intermediate data (just in case this happens again...we can put it on the repo and have folks pull it directly that way).

```
```{r download-nldi}

# see what data is available for a station:
dataRetrieval::whatNWISdata(siteNumber = usgs_stations_30km$identifier, 
                            service = "dv", 
                            parameterCd = c("00060", "00010"),
                            statCd = "00003")


# Extract Streamflow for identified sites
Q <- readNWISdv(usgs_stations_30km$identifier, 
                parameterCd = "00060", 
                startDate = "1960-10-01") %>% 
  renameNWISColumns()

wTemp <- readNWISdv(usgs_stations_30km$identifier, 
                parameterCd = "00010", 
                startDate = "1960-10-01") %>% 
  renameNWISColumns()
```

**Comment by ryanpeek** [comment]
Going to close this as I think it's been resolved.
