### ISSUE TITLE
intro module 3 creating projects was hard to pick up 

### ISSUE THREAD

**Issue by richpauloo** [r4wrds/r4wrds#89]
This section is a bit sparse, perhaps some screen shots and creating a directory to store the project.

Consider picking a location where people start, like:

1. make a folder on desktop called `intro_r4wrds`
2. walk through steps of creating a new project and put it in this folder
3. go to the folder and open the .Rproj file

**Comment by ryanpeek** [comment]
Potentially start with creating the project earlier (even at the beginning of the intro to Rstudio section), then walk through orienting to Rstudio, then move to lesson on project management (but already can have a project that we are part of), that way can focus a bit more on the file naming and folder structure in a project without having to get caught? Or at least put project creation at the very beginning of the proj management lesson...

**Comment by ryanpeek** [comment]
We've since reorganized and updated the project creation component and it seems to have helped this. Closing this issue.
